version: '3.7'

services:
  grpc-service:
    image: grpc-service
    build:
      context: .
      dockerfile: src/Grpc.Service/Dockerfile
    ports:
      - "5000:80"
    networks:
      - grpc-network

  grpc-client:
    image: grpc-client
    build:
      context: .
      dockerfile: src/Grpc.Client/Dockerfile
    environment:
      - GrpcServiceHost=http://grpc-service
    ports:
      - "5003:80"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge